version: "2"
services:
  desktop:
    build: .
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - $HOME/.local/share/hmcl:/home/hmcl/.local/share/hmcl
      - $HOME/Games/Minecraft/.minecraft:/home/hmcl/.minecraft
      - /dev/dri:/dev/dri
    #network_mode: "host"
